[package]
name = "oxideav-mp2"
version = "0.0.10"
edition = "2021"
rust-version = "1.80"
license = "MIT"
repository = "https://github.com/OxideAV/oxideav-mp2"
authors = ["Mark Karpeles"]
description = "Pure-Rust MPEG-1 / MPEG-2 LSF Audio Layer II (MP2) encoder and decoder"

readme = "README.md"
homepage = "https://github.com/OxideAV/oxideav-mp2"
keywords = ["multimedia", "audio", "mpeg", "mp2", "codec"]
categories = ["multimedia::encoding", "multimedia::audio"]

[dependencies]
oxideav-core = "0.1"

[patch.crates-io]
oxideav-core = { git = "https://github.com/ayooooo123/oxideav-core", rev = "9a314bf862480d019dc1133847ff6262d14ba628" }
